Versão de Raphael Soares
sizebay/frontend-challenge pull request #14
Opened 2023-01-19 22:21 UTC by Raphael-Soares

Construí a aplicação com Vite, utilizei a biblioteca styled-components assim com solicitado e utilizei também react-icons.

2023-01-20 14:36 UTC, vaporwavie commented
oi @Raphael-Soares! você consegue subir o seu projeto no Vercel para fazermos o QA?

2023-01-20 15:50 UTC, Raphael-Soares commented
Olá, com certeza! Aqui está o projeto na Vercel

https://frontend-challenge-blue.vercel.app/

Em sex., 20 de jan. de 2023 às 11:36, Luiz Nickel ***@***.***>
escreveu:

> oi @Raphael-Soares <https://github.com/Raphael-Soares>! você consegue
> subir o seu projeto no Vercel para fazermos o QA?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sizebay/frontend-challenge/pull/14#issuecomment-1398479179>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU22BQWJ4DKR7EUZGA44X5DWTKPIHANCNFSM6AAAAAAUA32ZJY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-24 19:05 UTC, vaporwavie requested changes
Obrigado pelo envio do seu desafio @Raphael-Soares! Deixei alguns pontos de melhoria para o seu código. Fico no aguardo para fazer o CR novamente!

Ah, uma dica legal:

nit: você pode converter seu Context num hook customizado pra evitar overhead.

Tipo usar `useApp()` que insancia o seu `useContext`.

2023-01-24 19:05 UTC, vaporwavie commented on src/components/Messages.jsx
> +            )}
ref: isso pode ser convertido em um único retorno, aproveitando as verificações mas retornando o mesmo componente, ao invés de duplicá-lo.

2023-01-24 19:05 UTC, vaporwavie commented on src/components/ProgressBar.jsx
> +    const progress = ((done.length / all) * 100).toFixed(0);
ref: você pode converter o `done` e `progress` em wrappers com o `useMemo` para evitar excesso de cálculo do browser.

2023-01-24 23:51 UTC, Raphael-Soares commented
Olá @vaporwavi, realizei as mudanças e alguns outros pequenos ajustes e optei por manter o Context.

2023-07-27 12:15 UTC, closed without merging