whole projecy
sizebay/frontend-challenge pull request #16
Opened 2023-01-20 15:41 UTC by hpozza

O que consegui fazer nas horas vagas

2023-01-23 15:24 UTC, hpozza commented
Bom dia!

segue o link:

https://frontend-challenge-4tzk.vercel.app/

Boa semana!



On Mon, Jan 23, 2023 at 11:29 AM Luiz Nickel ***@***.***>
wrote:

> oi @hpozza <https://github.com/hpozza>! você consegue subir o seu projeto
> no Vercel para fazermos o QA?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sizebay/frontend-challenge/pull/16#issuecomment-1400440427>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK5EEZELPYD2OEVWK2TKRITWT2ITPANCNFSM6AAAAAAUBVINGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-23 19:57 UTC, hpozza commented
Oi Luiz, me candidatei para a vaga de front-end.

Em seg, 23 de jan de 2023 16:14, Luiz Nickel ***@***.***>
escreveu:

> @hpozza <https://github.com/hpozza> você enviou o PR somente para
> avaliação técnica ou está se candidatando também a vaga de front-end?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sizebay/frontend-challenge/pull/16#issuecomment-1400848389>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK5EEZDZRKW2ZM3VPYZONLTWT3KCRANCNFSM6AAAAAAUBVINGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-24 00:00 UTC, vaporwavie commented
@hpozza entendi! Você gostaria de mais alguns dias para focar na finalização do projeto? Fizemos a análise aqui, mas o desafio possui requesitos que estão incompletos e vão contra a eficácia no Code Review :(

Quanto tempo tu achas que precisa para chegar na finalização?

2023-01-24 18:47 UTC, vaporwavie requested changes
Aplicando review só para pontuar que estamos aguardando resposta do @hpozza sobre continuidade ou não do desafio, com prazo extendido oferecido.

2023-01-24 19:45 UTC, hpozza commented
Opa, até sexta de noite te entrego

2023-01-24 20:04 UTC, vaporwavie commented
@hpozza happy hacking!

2023-07-27 12:15 UTC, closed without merging