Breno Santos
sizebay/frontend-challenge pull request #17
Opened 2023-01-20 21:45 UTC by breno5g

2023-01-20 22:44 UTC, vaporwavie commented
oi @breno5g! você consegue subir o seu projeto no Vercel para fazermos o QA?

2023-01-20 22:49 UTC, breno5g commented
> oi @breno5g! você consegue subir o seu projeto no Vercel para fazermos o QA?
> 
> 
> 
> 

Estava editando o readme para colocar o link, mas segue abaixo.

https://frontend-challenge-5zq30w9dn-breno5g.vercel.app/

2023-01-21 13:59 UTC, breno5g commented
Adicionando no readme informações sobre como rodar a aplicação.

2023-01-24 18:27 UTC, viniciusbe requested changes
Eae @breno5g, gostei que você fez os testes e usou o storybook! A única ressalva sobre o projeto é que um dos testes falhou.

2023-01-24 18:30 UTC, breno5g commented
Realmente, o teste relacionado a barra de progresso tem uma falha, pois depois de pronto adicionei a lib do react confetti. Ai acabei esquecendo de fazer o mock da instancia do canvas que é criado em 100%.

2023-01-24 18:31 UTC, breno5g commented
> Eae @breno5g, gostei que você fez os testes e usou o storybook! A única ressalva sobre o projeto é que um dos testes falhou. 

Realmente, o teste relacionado a barra de progresso tem uma falha, pois depois de pronto adicionei a lib do react confetti. Ai acabei esquecendo de fazer o mock da instancia do canvas que é criado em 100%.

2023-01-24 18:49 UTC, viniciusbe commented
Massa! Testei aqui, funcionando certinho!

2023-01-25 13:38 UTC, viniciusbe approved these changes

2023-01-25 13:46 UTC, closed without merging