Teste Frontend Challenge - Rafael Rodrigues
sizebay/frontend-challenge pull request #19
Opened 2023-01-23 17:45 UTC by rafaelwr

Teste Frontend Challenge para candidatura de emprego na Sizebay.

Feito por Rafael Rodrigues.

2023-01-23 18:06 UTC, vaporwavie commented
oi @rafaelwr! você consegue subir o seu projeto no Vercel para fazermos o QA?

2023-01-23 18:32 UTC, rafaelwr commented
> oi @rafaelwr! você consegue subir o seu projeto no Vercel para fazermos o QA?

Sim. Segue abaixo o link (enviei também por e-mail):
https://sizebay-frontend-challenge.vercel.app/

2023-01-25 14:10 UTC, viniciusbe commented on src/context/ItemsContext.js
> +        document.querySelector('#filter-pending').classList.remove('selected')
Acho que uma abordagem melhor para fazer a estilização condicional seria utilizar o styled-components, passando as condições por props.

2023-01-25 14:13 UTC, viniciusbe commented on src/context/ItemsContext.js
> +            }
Acredito que você consegue refator essa lógica para que não precise dessa cadeia de `if/else`.

2023-01-25 14:15 UTC, viniciusbe commented on src/components/ItemsList.js
> +
Sugiro tentar outra abordagem para mostrar os items filtrados, talvez salvar em uma variavel.

2023-01-25 14:29 UTC, viniciusbe commented on src/components/Search.js
> +            }
É possível refatorar essas lógicas do `setDoneSelected` e `setPendingSelected` sem precisar do `if/else`

2023-01-25 14:39 UTC, viniciusbe commented on src/components/Search.js
> +                    item.show = false
Mesmo de https://github.com/sizebay/frontend-challenge/pull/19/files#r1086711181

2023-01-25 14:50 UTC, viniciusbe requested changes
Gostei muito da usabilidade do projeto, está funcionando certinho! Tenho alguns pontos que podem melhorar no código:

- Veja que alguma vezes você faz um `filter` nos items, seria interessante então guardar esse resultado para reutilizar.
- Seria legal criar arquivos  para separar o css do restante, melhorando a organização.
- Outros pontos específicos estão comentados no código.

2023-01-26 20:01 UTC, rafaelwr commented
> Gostei muito da usabilidade do projeto, está funcionando certinho! Tenho alguns pontos que podem melhorar no código:
> 
> * Veja que alguma vezes você faz um `filter` nos items, seria interessante então guardar esse resultado para reutilizar.
> * Seria legal criar arquivos  para separar o css do restante, melhorando a organização.
> * Outros pontos específicos estão comentados no código.

2023-01-26 20:02 UTC, rafaelwr commented
@viniciusbe , boa tarde. Fiz o push nos ajustes solicitados. Qualquer dúvida estou à disposição.

2023-01-27 13:38 UTC, viniciusbe approved these changes
Tudo certo @rafaelwr , obrigado!

2023-01-27 13:38 UTC, closed without merging