Development
sizebay/frontend-challenge pull request #20
Opened 2023-01-23 19:52 UTC by KiF1

2023-01-24 00:04 UTC, vaporwavie commented
oi @KiF1! você consegue subir o seu projeto no Vercel para fazermos o QA?

2023-01-24 00:11 UTC, KiF1 commented
Opa, consigo sim. O link: https://tasks-ts.vercel.app/

Em seg, 23 de jan de 2023 21:04, Luiz Nickel ***@***.***>
escreveu:

> Assigned #20 <https://github.com/sizebay/frontend-challenge/pull/20> to
> @KiF1 <https://github.com/KiF1>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sizebay/frontend-challenge/pull/20#event-8339302203>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXDNFHJLTF5EZWVOO6DYVMTWT4MCRANCNFSM6AAAAAAUEH3GBI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-01-25 17:18 UTC, viniciusbe commented on tasks/src/pages/Tasks/index.tsx
> +                )}
Achei essa lógica um pouco confusa, você conseguiria refazê-la em uma única iteração. Sugiro utilizar apenas uma variável para guardar os items filtrados.

2023-01-25 17:19 UTC, viniciusbe requested changes
Eae @KiF1 , legal que você usou o `react-hook-form` com validação. Só queria apontar alguns ajustes que iriam melhorar seu projeto:

- A pesquisa por texto não está funcionando.
- A barra de progresso deveria se preencher de acordo a evolução das tasks concluídas, e não o contrário.
- Outros pontos específicos estão comentados no código.

2023-01-25 17:53 UTC, KiF1 commented
Opa, sobre o código, como você falou, olhando bem daria para dar uma
refatorada bem legal mesmo fazendo um componente e fazendo o ternário
dentro dele, deixando a index mais limpa. Sobre a pesquisa, eu testei e
está funcionando, só precisa enviar com o botão enter. E sobre a barra, eu
acho que entendi o design de forma errada msm, mas obg pelas observações
serão de grande valia.

Em qua, 25 de jan de 2023 14:19, Vinícius Bernardes <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> Eae @KiF1 <https://github.com/KiF1> , legal que você usou o
> react-hook-form com validação. Só queria apontar alguns ajustes que iriam
> melhorar seu projeto:
>
>    - A pesquisa por texto não está funcionando.
>    - A barra de progresso deveria se preencher de acordo a evolução das
>    tasks concluídas, e não o contrário.
>    - Outros pontos específicos estão comentados no código.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sizebay/frontend-challenge/pull/20#pullrequestreview-1269784260>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXDNFHJ53EFJISVSRZHEJW3WUFOBBANCNFSM6AAAAAAUEH3GBI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-25 19:23 UTC, viniciusbe commented
Você gostaria de fazer as correções ou posso dar o desafio como concluído?

2023-01-25 19:24 UTC, KiF1 commented
Posso sim fazer as correções, quanto tempo eu teria pra enviar?

Em qua, 25 de jan de 2023 16:23, Vinícius Bernardes <
***@***.***> escreveu:

> Você gostaria de fazer as correções ou posso dar o desafio como concluído?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sizebay/frontend-challenge/pull/20#issuecomment-1404118661>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXDNFHMOP7GNBCBTU4G4KILWUF4TRANCNFSM6AAAAAAUEH3GBI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-25 19:31 UTC, viniciusbe commented
Beleza, até sexta-feira.

2023-01-25 20:28 UTC, KiF1 commented
Opa, as alterações já foram concluídas. Agora sim está tudo ok. Já subi
para o repositório e as alterações já estão no ar

Em qua, 25 de jan de 2023 16:32, Vinícius Bernardes <
***@***.***> escreveu:

> Beleza, até sexta-feira.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sizebay/frontend-challenge/pull/20#issuecomment-1404127616>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXDNFHMQZTYFNDXKBTALUOLWUF5TDANCNFSM6AAAAAAUEH3GBI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-26 12:00 UTC, viniciusbe commented
Beleza @KiF1 , obrigado!

2023-01-26 12:01 UTC, viniciusbe approved these changes

2023-01-26 12:01 UTC, closed without merging