Review desafio
sizebay/frontend-challenge pull request #21
Opened 2023-01-23 20:36 UTC by marcusicaro

Segue a review com os aprimoramentos sugeridos pelo @viniciusbe e outros que eu havia feito para testes.

Atenciosamente.

2023-01-23 21:19 UTC, marcusicaro commented
Preview: https://marcusicaro.github.io/frontend-challenge/

2023-01-24 00:01 UTC, vaporwavie commented
Oi @marcusicaro obrigado! Só peço que, para evitar conflitos de assinatura nos PRs, mantém o pos-qa do @viniciusbe no mesmo contexto. Não precisa abrir outro!

2023-01-24 13:00 UTC, marcusicaro commented
> Oi @marcusicaro obrigado! Só peço que, para evitar conflitos de assinatura nos PRs, mantém o pos-qa do @viniciusbe no mesmo contexto. Não precisa abrir outro!

Opa, foi mal. Pode deixar :+1:

2023-01-24 17:04 UTC, viniciusbe commented
@marcusicaro Show mano, gostei que você usou `if` ternário! Só ficou faltando mesmo colocar uma altura máxima para as tarefas.

2023-01-24 18:44 UTC, vaporwavie requested changes
@marcusicaro 
Aplicando review aqui só pra pontuar que estamos aguardando você inserir uma altura máxima para as tarefas!

2023-01-24 21:20 UTC, marcusicaro commented
Opa, realmente, tinha esquecido de adicionar uma max-height.

Fiz de um jeito que achei que ficou bem legal, deixando o overflow scroll e dando uma max-height somente pra lista das tasks.

Acredito que agora esteja finalizado, se for só isso mesmo, foi muito bacana participar desse projeto com vocês @viniciusbe e @vaporwavie macintosh plus!

Preview: https://marcusicaro.github.io/frontend-challenge/

2023-01-25 13:36 UTC, viniciusbe commented
Valeu @marcusicaro , agora está finalizado, obrigado!

2023-01-25 18:17 UTC, vaporwavie reviewed
(approving)

2023-01-25 18:18 UTC, vaporwavie approved these changes

2023-01-25 18:18 UTC, closed without merging