Elton - Frontend Challenge
sizebay/frontend-challenge pull request #22
Opened 2023-01-24 03:50 UTC by elton-souza

Finalizado o desafio e feito o deploy da aplicação!
Deploy: https://sizebay-frontend-challenge-phi.vercel.app/

2023-01-24 19:15 UTC, vaporwavie requested changes
@elton-souza obrigado por enviar o seu desafio! O seu uso do styled-components foi muito bem realizado e não tenho o que comentar sobre isso. Os demais pontos estão descritos no meu review.

Quando estiver pronto, fazemos o CR novamente!

2023-01-24 19:15 UTC, vaporwavie commented on src/components/DateTask/index.tsx
> +    </Header>
ref: se a intenção é extrair os dados do `date`, ao invés de consultar diretamente o index de cada valor, você pode encontrá-los dinamicamente, assim:

```js
const [day, month, year, week] = format(new Date(), "dd-MMM-yyyy-EEEE").split("-");
```

E aí no seu render é só chamar essas variáveis.

2023-01-24 19:15 UTC, vaporwavie commented on src/components/ListTask/index.tsx
> +}
ref: @elton-souza esse componente acabou ficando um pouco verboso. Tente separar as responsabilidades em componentes menores pra garantir uma leitura mais concisa do que você está tentando compor! 

PS: o uso do Context API pode te ajudar bastante nisso.
PPS: evite tratar os eventos diretamente no escopo do elemento. Busque separar as responsabilidades.

2023-01-24 19:15 UTC, vaporwavie commented on src/components/ProgressBar/index.tsx
> +
ref: `percentageProgress` pode ser modificado para ter um wrapper do `useMemo`, afim de evitar problemas de memória no browser.

2023-01-24 19:15 UTC, vaporwavie commented on src/pages/Home/index.tsx
> +}
@elton-souza por esse componente ser o principal, ele acabou arrecando responsabilidades demais e dificultou o processo de leitura e até mesmo potenciais leaks de renderização. Tente separar um pouco os componentes e evite mesclar muitas ações/eventos num lugar só.

2023-01-25 01:44 UTC, elton-souza commented
Alterações feitas!

2023-01-25 12:25 UTC, vaporwavie reviewed
Obrigado @elton-souza! A refatoração ficou muito boa. LGTM! 🎉 

Entraremos em contato em breve. Abraço!

2023-01-25 18:18 UTC, vaporwavie commented
(approving)

2023-01-25 18:19 UTC, vaporwavie approved these changes

2023-01-25 18:19 UTC, closed without merging