Challange Completed -André Fidelis
sizebay/frontend-challenge pull request #24
Opened 2023-01-24 23:51 UTC by FidelissJr

link do projeto: [](https://frontend-challenge-mfpngbjau-fidelissjr.vercel.app/)

2023-01-25 18:33 UTC, viniciusbe commented on size_challenge/src/components/Filters.js
> +    const [status, setStatus] = useState("Pending")
Você não precisa criar outro estado para o status aqui, poderia usar o do componente pai

2023-01-25 18:37 UTC, viniciusbe commented on size_challenge/src/layouts/TaskMenu.js
> +        ])
Veja que esse padrão de uso do `setTasks` e `setFilteredTasks` juntos se repetem 4 vezes nesse componente, acredito que há maneiras de refatorar a fim de evitar essa repetição.

2023-01-25 18:53 UTC, viniciusbe commented on size_challenge/src/components/Filters.js
> +                        clearButton ? <BsFillXCircleFill size={20} color="#8D8D8D" onClick={onSearchTask}/> : <FaSearch size={20} opacity={.5}/>
Não é preciso usar um estado para saber se o `searchValue` esta vazio, apenas uma variável bastaria. Além disso você está usando a mesmo função `onSearchTask` para o `onClick` e `onChange`, esses eventos esperam funções com tipos, seria mais correto ter uma função para cada.

2023-01-25 19:02 UTC, viniciusbe commented on size_challenge/src/components/InputItem.js
> +        <Container color={color} large="100" margin="20px 0 20px 0" onFocus={turnInputOn} onBlur={turnInputOff}>
Em vez de controlar o estilo por estados, é possível fazer isso apenas com css : https://developer.mozilla.org/pt-BR/docs/Web/CSS/:focus

2023-01-25 19:10 UTC, viniciusbe commented on size_challenge/src/components/TaskCard.js
> +                <Container id={props.task.id} data-tooltip-content="Edit Task"color={color} large="100" margin="8px 0 0 0" onMouseOver={setShowOn} onMouseOut={setShowOff}>
Mesmo caso do https://github.com/sizebay/frontend-challenge/pull/24/files#r1087062702

2023-01-25 19:18 UTC, viniciusbe requested changes
Opa @FidelissJr , obrigado pelo seu tempo dedicado ao desafio! Achei alguns pontos que podem melhorar seu código:

- Seria legal criar arquivos para separar o css do restante do código, melhorando a organização.
- Outros pontos específicos estão comentados no código.

2023-01-25 22:18 UTC, FidelissJr commented
Fala @viniciusbe, valeu pela revisão. Beleza,  vou ajustar o código conforme as sugestões.

2023-01-26 12:13 UTC, viniciusbe commented
Obrigado @FidelissJr !

2023-01-26 12:13 UTC, viniciusbe approved these changes

2023-01-26 12:14 UTC, closed without merging