Desafio Front-end de Renan Iomes
sizebay/frontend-challenge pull request #26
Opened 2023-01-26 03:57 UTC by iomes2

- Este foi um desafio da empresa sizebay.
- Obs: Para melhor funcionamento dos métodos responsivos, baixar o repositório e rodar localmente o site. O Vercel não está conseguindo distribuir de maneira correta a responsividade.

2023-01-26 18:03 UTC, viniciusbe requested changes
Eae @iomes2 , gostei do seu desafio em geral! Seguem algumas melhorias que você pode fazer:

- Senti falta da edição do conteúdo da task.
- Seria interessente separar o css dos arquivos, ficaria mais organizado.
- Outros pontos mais específicos então comentados no código.

2023-01-26 18:05 UTC, viniciusbe commented on src/index.js
> +}
O `context` poderia ficar em arquivo separado, ficaria mais organizado.

2023-01-26 18:06 UTC, viniciusbe commented on src/index.js
> +  }
Não é necessário usar o `useReducer` nesse caso, apenas guardar o filteredTasks numa variável seria suficiente

2023-01-26 18:07 UTC, viniciusbe commented on src/components/header/Header.js
> +  }
Poderia usar o `new Date().toLocaleString("en-US", { weekday: "long" })` para pegar o dia de semana

2023-01-28 01:04 UTC, iomes2 commented
Efetuei todas as melhorias e correções que você me sugeriu. Nome do commit: final version fixed

2023-01-30 12:52 UTC, viniciusbe approved these changes
Obrigado @iomes2 !

2023-01-30 12:52 UTC, closed without merging